# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Career',
                'db_table': 'careers',
                'managed': False,
                'verbose_name_plural': 'Careers',
            },
        ),
        migrations.CreateModel(
            name='Doctype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abreviatura', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'verbose_name': 'Doctype',
                'db_table': 'doctypes',
                'managed': False,
                'verbose_name_plural': 'Doctypes',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nombre_corto', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Institute',
                'db_table': 'institutes',
                'managed': False,
                'verbose_name_plural': 'Institutes',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_expediente', models.TextField(blank=True, null=True)),
                ('documento', models.CharField(blank=True, max_length=10, null=True)),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('registro_facultad', models.CharField(max_length=50)),
                ('registro_universidad', models.CharField(max_length=50)),
                ('libro', models.IntegerField(blank=True, null=True)),
                ('pagina', models.IntegerField(blank=True, null=True)),
                ('tomo', models.IntegerField()),
                ('fecha_ultimo_examen', models.DateField(blank=True, null=True)),
                ('fecha_entrada', models.DateField(blank=True, null=True)),
                ('fecha_pase_imprenta', models.DateField(blank=True, null=True)),
                ('fecha_expedicion', models.DateField()),
                ('nro_resolucion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_pase_facultad', models.DateField(blank=True, null=True)),
                ('nro_envio', models.TextField(blank=True, null=True)),
                ('fecha_regreso', models.DateField(blank=True, null=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('apellido_canonico', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Order',
                'db_table': 'orders',
                'managed': False,
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=15, unique=True)),
                ('hashed_password', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'users',
                'managed': False,
                'verbose_name_plural': 'Users',
            },
        ),
    ]
