# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_create_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'verbose_name': 'Orden', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': 'Usuario', 'verbose_name_plural': 'Users'},
        ),
    ]
