# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_change_meta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'managed': True, 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='doctype',
            options={'managed': True, 'verbose_name': 'Tipo Documento', 'verbose_name_plural': 'Tipos Documentos'},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'managed': True, 'verbose_name': 'Facultad', 'verbose_name_plural': 'Facultades'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True, 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
