# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_change_meta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='institute',
            field=models.ForeignKey(default=0,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='app.Institute', verbose_name='Facultad'),
        ),
        migrations.AddField(
            model_name='order',
            name='career',
            field=models.ForeignKey(default=0,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='app.Career', verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='order',
            name='doctype',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='app.Doctype', verbose_name='Tipo Documento'),
        ),
    ]
