# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apellido_canonico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido can\xf3nico'),
        ),
        migrations.AlterField(
            model_name='order',
            name='doctype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Doctype', verbose_name='Tipo Documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='documento',
            field=models.CharField(default=0, max_length=10, verbose_name='Nro documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha expedici\xf3n'),
        ),
        migrations.AlterField(
            model_name='order',
            name='nro_expediente',
            field=models.TextField(default=0, verbose_name='Nro expediente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='tomo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tomo'),
        ),
    ]
