# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='descripcion',
            field=models.TextField(default=' ', verbose_name='Descripci\xf3n'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctype',
            name='abreviatura',
            field=models.CharField(default=' ', max_length=4, verbose_name='abreviatura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institute',
            name='descripcion',
            field=models.TextField(default=' ', verbose_name='Descripci\xf3n'),
            preserve_default=False,
        ),
    ]
